version: "3.2"

services:

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: testdb
    ports:
      - "33066:3306"